# Generated by Django 3.1.5 on 2021-01-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('uploaded_time', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('year', models.FloatField()),
                ('county_name', models.CharField(max_length=20)),
                ('state_code', models.CharField(max_length=10)),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
    ]
